# Generated by Django 5.0.7 on 2024-08-09 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turntable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turntablemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 9, 47, 37, 476080)),
        ),
    ]
