# Generated by Django 5.0.7 on 2024-08-09 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turntable', '0002_alter_turntablemodel_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turntablemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 9, 48, 41, 365329)),
        ),
    ]
