# Generated by Django 5.0.7 on 2024-08-09 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turntable', '0003_alter_turntablemodel_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turntablemodel',
            name='blocks_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turntablemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 13, 57, 1, 371698)),
        ),
        migrations.AlterField(
            model_name='turntablemodel',
            name='cycle',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turntablemodel',
            name='interval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turntablemodel',
            name='participate_condition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turntablemodel',
            name='reward_currency',
            field=models.CharField(max_length=100),
        ),
    ]
