# Generated by Django 5.0.7 on 2024-08-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='data',
            field=models.JSONField(default=[{}]),
        ),
    ]
